extensions:

receivers:
  otlp:
    protocols:
      grpc:

processors:
  routing:
    default_exporters: [logging]
    error_mode: ignore
    table:
      - statement: route() where resource.attributes["attr1"] == "demo"
        exporters: [ logging/route-1 ]
      - statement: route() where resource.attributes["attr1"] == "demo" and resource.attributes["attr2"] == "xxx" 
        exporters: [ logging/route-2 ]

exporters:
  logging:
  logging/route-1:
  logging/route-2:

connectors:

service:
  extensions:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [routing]
      exporters: [logging, logging/route-1, logging/route-2]