apiVersion: v1
kind: Pod
metadata:
  name: my-microservice
spec:
  containers:
  - name: my-microservice
    image: my-org/my-microservice:v0.0.0
    ports:
    - containerPort: 8080
      protocol: TCP
  - name: sidecar
    image: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector:0.67.0
    ports:
    - containerPort: 8888
      name: metrics
      protocol: TCP
    - containerPort: 4317
      name: otlp-grpc
      protocol: TCP
    args:
    - --config=/conf/collector.yaml
    volumeMounts:
    - mountPath: /conf
      name: sidecar-conf
  volumes:
  - name: sidecar-conf
    configMap:
      name: sidecar-for-my-workload
      items:
      - key: collector.yaml
        path: collector.yaml