kind: ConfigMap
metadata:
  name: grafana-agent-logs
  namespace: default
apiVersion: v1
data:
  agent.yaml: |
    metrics:
      wal_directory: /tmp/grafana-agent-wal
      global:
        scrape_interval: 60s
        external_labels:
          cluster: local-k3d
      configs:
      - name: integrations
        remote_write:
        - url: https://prometheus-prod-13-prod-us-east-0.grafana.net/api/prom/push
          basic_auth:
            username: 1120448
            password: glc_eyJvIjoiMSIsIm4iOiJ0b2tlbi1rOHMtYWdlbnQiLCJrIjoiSXM1blRDOTIwMFptZTkzNW42Y3diS0U0IiwibSI6eyJyIjoicHJvZC11cy1lYXN0LTAifX0=
    integrations:
      prometheus_remote_write:
      - url: https://prometheus-prod-13-prod-us-east-0.grafana.net/api/prom/push
        basic_auth:
          username: 1120448
          password: glc_eyJvIjoiMSIsIm4iOiJ0b2tlbi1rOHMtYWdlbnQiLCJrIjoiSXM1blRDOTIwMFptZTkzNW42Y3diS0U0IiwibSI6eyJyIjoicHJvZC11cy1lYXN0LTAifX0=
    
    logs:
      configs:
      - name: integrations
        clients:
        - url: https://logs-prod-006.grafana.net/loki/api/v1/push
          basic_auth:
            username: 659325
            password: glc_eyJvIjoiMSIsIm4iOiJ0b2tlbi1rOHMtYWdlbnQiLCJrIjoiSXM1blRDOTIwMFptZTkzNW42Y3diS0U0IiwibSI6eyJyIjoicHJvZC11cy1lYXN0LTAifX0=
          external_labels:
            cluster: local-k3d
        positions:
          filename: /tmp/positions.yaml
        target_config:
          sync_period: 10s
        scrape_configs:
        - job_name: integrations/kubernetes/pod-logs
          kubernetes_sd_configs:
            - role: pod
          pipeline_stages:
            - docker: {}
          relabel_configs:
            - source_labels:
                - __meta_kubernetes_pod_node_name
              target_label: __host__
            - action: replace
              replacement: $1
              separator: /
              source_labels:
                - __meta_kubernetes_namespace
                - __meta_kubernetes_pod_name
              target_label: job
            - action: replace
              source_labels:
                - __meta_kubernetes_namespace
              target_label: namespace
            - action: replace
              source_labels:
                - __meta_kubernetes_pod_name
              target_label: pod
            - action: replace
              source_labels:
                - __meta_kubernetes_pod_container_name
              target_label: container
            - replacement: /var/log/pods/*$1/*.log
              separator: /
              source_labels:
                - __meta_kubernetes_pod_uid
                - __meta_kubernetes_pod_container_name
              target_label: __path__
