extensions:
  basicauth/traces:
    client_auth:
      username: "239237"
      password: "..."

processors:
  batch:

receivers:
  otlp:
    protocols:
      grpc:

exporters:
  debug:
    verbosity: detailed
  otlphttp:
    endpoint: https://otlp-gateway-prod-us-central-0.grafana.net/otlp
    auth:
      authenticator: basicauth/traces

service:
  extensions: [ basicauth/traces ]
  pipelines:
    traces:
      receivers:  [ otlp ]
      processors: [  ]
      exporters:  [ otlphttp ]
    metrics:
      receivers:  [ otlp ]
      processors: [  ]
      exporters:  [ debug, otlphttp ]
