extensions:
  basicauth/logs:
    client_auth:
      username: "${LOGS_USER_ID}"
      password: "${TOKEN}"   

receivers:
  journald:
    directory: /var/log/journal

exporters:
  loki:
    endpoint: "${LOGS_URL}"
    auth:
      authenticator: basicauth/logs

service:
  extensions: [ basicauth/logs ]
  pipelines:
    logs:
      receivers:  [ journald ]
      processors: [ ]
      exporters:  [ loki ]
