receivers:
  journald:
    directory: /var/log/journal/a04e3a44cdd740f88d6a7ae3bb8c70cf

exporters:
  logging:
    loglevel: debug
  loki:
    endpoint: http://localhost:3100/loki/api/v1/push
    tls:
      insecure: true
    labels:
      attributes:
        host.name: host_name 
    format: json
    tenant:
      source: attributes
      value: tenant

processors:
  attributes:
    actions:
    - action: insert
      key: host.name
      value: guarana
  resource:
    attributes:
    - action: insert
      key: tenant
      value: globex

extensions:

service:
  extensions:
  pipelines:
    logs:
      receivers: [journald]
      processors: [attributes, resource]
      exporters: [logging, loki]
