receivers:
  journald:
    directory: /var/log/journal/a04e3a44cdd740f88d6a7ae3bb8c70cf

exporters:
  logging:
    loglevel: debug
  loki:
    endpoint: https://logs-prod-us-central1.grafana.net/loki/api/v1/push
    headers:
      authorization: Basic ODc5NDA6ZXlKcklqb2labVpsWWpsaE56SXpPRGRsTW1aalpXRTBOVGN3TVRkbU16VXlNakl4TUdJellqYzBNbVEzTVNJc0ltNGlPaUpqYjJ4c1pXTjBiM0lpTENKcFpDSTZOVEk1TXpjeGZRPT0=
    labels:
      attributes:
        host.name: host_name 
    format: json
    tenant:
      source: attributes
      value: tenant

processors:
  attributes:
    actions:
    - action: insert
      key: host.name
      value: guarana
  resource:
    - action: insert
      key: tenant
      value: acme

extensions:

service:
  extensions:
  pipelines:
    logs:
      receivers: [journald]
      processors: [attributes, resource]
      exporters: [logging, loki]
