apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otelcol-server
spec:
  image: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:0.101.0
  replicas: 5
  config:
    receivers:
      otlp:
        protocols:
          grpc: {}

    exporters:
      nop: {}

    service:
      extensions: [ ]
      pipelines:
        traces:
          receivers:  [ otlp ]
          processors: [  ]
          exporters:  [ nop ]
        logs:
          receivers:  [ otlp ]
          processors: [  ]
          exporters:  [ nop ]
        metrics:
          receivers:  [ otlp ]
          processors: [  ]
          exporters:  [ nop ]
      telemetry:
        metrics:
          level: detailed
          readers:
            - periodic:
                exporter:
                  otlp:
                    endpoint: https://otlp-gateway-prod-eu-west-2.grafana.net/otlp/v1/metrics
                    protocol: http/protobuf
                    headers:
                      Authorization: "Basic ..."
