apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: backends
  namespace: observability
spec:
  replicas: 5
  config: |
    receivers:
      otlp:
        protocols:
          grpc:

    processors:
      tail_sampling:

    exporters:
      otlp/grafanacloud:
    
    connectors:
      spanmetrics:
      servicegraph:
      forward:

    service:
      pipelines:
        traces:
          receivers:
            - otlp
          processors: []
          exporters:
            - spanmetrics
            - servicegraph
            - forward
        traces/grafanacloud:
          receivers:
            - forward
          processors:
            - tail_sampling
          exporters:
            - otlp/grafanacloud
        metrics/grafanacloud:
          receivers:
            - spanmetrics
            - servicegraph
          processors: []
          exporters:
            - otlp/grafanacloud
